/**
 * This file was generated by scripts/generateRoutes.ts
 */
import { SafeAreaView } from "react-native-safe-area-context";
import { AboutScreen } from "@acme/app";

export default function About() {
  return (
    <SafeAreaView className="flex-1 bg-background">
      <AboutScreen />
    </SafeAreaView>
  );
}
